apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: sina-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sina-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sina-broker
    spec:
      containers:
        - name: sina-broker
          image: noisyboy9/bale_message_broker:latest
          ports:
            - name: prometheus
              containerPort: 8000
            - name: grpc
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: sina-broker-service
  labels:
    app.kubernetes.io/name: sina-broker
spec:
  type: NodePort
  ports:
    - name: prometheus
      port: 8000
      nodePort: 30002
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 9000
      nodePort: 30001
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: sina-broker

